spring:
  jpa:
    database: MYSQL
    showSql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost/rsmortgage
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
