spring:
  jpa:
    database: MYSQL
    showSql: true
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto:create-drop
        generate-ddl:true
  datasource:
    url: jdbc:mysql://localhost:3306/rsmortgage
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
